### ISSUE TITLE
Confirmation

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/express-api-deployment-guide#8]
How can we tell if the deployment is successful?
All the broswer says when i do ```heroku open``` at the end of the instruction is show the below characters at the top left of the site:
{"index":{"title":"Express Template","environment":"production"}}
Is that what it is supposed to be? there is no confirmation that it has been set properly.

**Comment by doremaxime** [comment]
I have tested it from the deployed front end and it doesn't work...

**Comment by doremaxime** [comment]
The error message displaying in the console when trying to sign in is:
```
XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://gzmj-survey.github.io' is therefore not allowed access. The response had HTTP status code 400.
```

I imagine that means there is a setting somewhere that would allow 'https://gzmj-survey.github.io'  to access heroku or we need to add an extra header?

**Comment by bernardlee** [comment]
> How can we tell if the deployment is successful?
> All the broswer says when i do heroku open at the end of the instruction is show the below characters at the top left of the site:
> {"index":{"title":"Express Template","environment":"production"}}
> Is that what it is supposed to be? there is no confirmation that it has been set properly.

This is correct.

> The error message displaying in the console when trying to sign in is:
> `XMLHttpRequest cannot load https://ga-wdi-boston.herokuapp.com/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://gzmj-survey.github.io' is therefore not allowed access. The response had HTTP status code 400.`
> I imagine that means there is a setting somewhere that would allow 'https://gzmj-survey.github.io' to access heroku or we need to add an extra header?

This should be in the [team-project issue queue](https://github.com/ga-wdi-boston/team-project/issues).  The error message gives you a hint about the problem.

**Comment by doremaxime** [comment]
Ok, i'll do it in the team project queue now that i know that Heroku was successful.
